"""add_ozon_spp_columns

Revision ID: 0ae7f848148c
Revises: 8e6515a78d5f
Create Date: 2026-07-09 16:05:53.290216

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae7f848148c'
down_revision: Union[str, None] = '8e6515a78d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_ozon_price_snapshot', sa.Column('buyer_regular_price_web', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('fact_ozon_price_snapshot', sa.Column('spp_rub', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('fact_ozon_price_snapshot', sa.Column('spp_percent', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_ozon_price_snapshot', 'spp_percent')
    op.drop_column('fact_ozon_price_snapshot', 'spp_rub')
    op.drop_column('fact_ozon_price_snapshot', 'buyer_regular_price_web')
    # ### end Alembic commands ###
