"""create_fact_vvbromo_product_day

Revision ID: 1740e3cb76da
Revises: 20260625_0023
Create Date: 2026-06-26 17:40:40.768763

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1740e3cb76da'
down_revision: Union[str, None] = '20260625_0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_vvbromo_product_day',
    sa.Column('fact_vvbromo_product_day_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_code', sa.Text(), nullable=True),
    sa.Column('organic_sales', sa.Integer(), nullable=True),
    sa.Column('operating_profit', sa.Numeric(), nullable=True),
    sa.Column('operating_profit_per_unit', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), server_default='vvbromo', nullable=False),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('fact_vvbromo_product_day_id', name=op.f('pk_fact_vvbromo_product_day')),
    sa.UniqueConstraint('day', 'nm_id', name='uq_fact_vvbromo_product_day_day_nm_id')
    )
    op.create_index('idx_fact_vvbromo_product_day_day_nm', 'fact_vvbromo_product_day', ['day', 'nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_vvbromo_product_day_day_nm', table_name='fact_vvbromo_product_day')
    op.drop_table('fact_vvbromo_product_day')
    # ### end Alembic commands ###
