"""add_fact_wb_statistics_order_size_day

Revision ID: 31b39255d27e
Revises: 20260705_0025
Create Date: 2026-07-05 23:38:40.151667

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b39255d27e'
down_revision: Union[str, None] = '20260705_0025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_wb_statistics_order_size_day',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('chrt_id', sa.BigInteger(), nullable=True),
    sa.Column('tech_size', sa.String(length=64), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('cancel_count', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_wb_statistics_order_size_day')),
    sa.UniqueConstraint('date', 'nm_id', 'barcode', name='uq_fact_wb_statistics_order_size_day_natural_key')
    )
    op.create_index('idx_fact_wb_statistics_order_size_day_date_nm', 'fact_wb_statistics_order_size_day', ['date', 'nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_wb_statistics_order_size_day_date_nm', table_name='fact_wb_statistics_order_size_day')
    op.drop_table('fact_wb_statistics_order_size_day')
    # ### end Alembic commands ###
