"""create_fact_ivan_stock_sheet_day

Revision ID: 48e2045abf80
Revises: 20260630_0024
Create Date: 2026-07-05 16:43:14.643449

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48e2045abf80'
down_revision: Union[str, None] = '20260630_0024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_ivan_stock_sheet_day',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_date', sa.Date(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('size_name', sa.Text(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('color_name', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('nomenclature_raw', sa.Text(), nullable=True),
    sa.Column('source_sheet', sa.Text(), server_default='Остатки', nullable=False),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_ivan_stock_sheet_day')),
    sa.UniqueConstraint('stock_date', 'nm_id', 'size_name', 'barcode', name='uq_fact_ivan_stock_sheet_day')
    )
    op.create_index('idx_fact_ivan_stock_sheet_day_date_nm', 'fact_ivan_stock_sheet_day', ['stock_date', 'nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_ivan_stock_sheet_day_date_nm', table_name='fact_ivan_stock_sheet_day')
    op.drop_table('fact_ivan_stock_sheet_day')
    # ### end Alembic commands ###
