"""add_communications_tables

Revision ID: 7c9c393f8861
Revises: 0ae7f848148c
Create Date: 2026-07-10 22:24:33.342603

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c9c393f8861'
down_revision: Union[str, None] = '0ae7f848148c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('promocode', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('chat_registry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('first_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sender', sa.String(length=50), nullable=True),
    sa.Column('reply_sign', sa.Text(), nullable=True),
    sa.Column('current_chat_exists', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_registry')),
    sa.UniqueConstraint('marketplace', 'chat_id', name='uq_chat_registry_marketplace_chat_id')
    )
    op.create_index('idx_chat_registry_marketplace_chat', 'chat_registry', ['marketplace', 'chat_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_status', sa.String(length=50), server_default='ready', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipients_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_recipients')),
    sa.UniqueConstraint('campaign_id', 'chat_id', name='uq_campaign_recipients_camp_chat')
    )
    op.create_index('idx_campaign_recipients_campaign', 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_table('send_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('send_status', sa.String(length=50), nullable=False),
    sa.Column('api_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_send_logs_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_send_logs'))
    )
    op.create_index('idx_send_logs_campaign', 'send_logs', ['campaign_id'], unique=False)
    op.create_index('idx_send_logs_chat', 'send_logs', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_send_logs_chat', table_name='send_logs')
    op.drop_index('idx_send_logs_campaign', table_name='send_logs')
    op.drop_table('send_logs')
    op.drop_index('idx_campaign_recipients_campaign', table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index('idx_chat_registry_marketplace_chat', table_name='chat_registry')
    op.drop_table('chat_registry')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
