"""add_fact_ozon_price_snapshot

Revision ID: 8e6515a78d5f
Revises: 20260706_0026
Create Date: 2026-07-09 15:41:55.366215

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e6515a78d5f'
down_revision: Union[str, None] = '20260706_0026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_ozon_price_snapshot',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('seller_status', sa.String(length=128), nullable=True),
    sa.Column('stock_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('seller_price_api', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('buyer_visible_price_web', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_bank_price_web', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('old_price_web', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('status_api', sa.String(length=128), nullable=True),
    sa.Column('status_web', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_fact_ozon_price_snapshot')),
    sa.UniqueConstraint('snapshot_at', 'offer_id', name='uq_fact_ozon_price_snapshot_at_offer_id')
    )
    op.create_index('idx_fact_ozon_price_snapshot_at_offer_id', 'fact_ozon_price_snapshot', ['snapshot_at', 'offer_id'], unique=False)
    op.create_index('idx_fact_ozon_price_snapshot_date', 'fact_ozon_price_snapshot', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_ozon_price_snapshot_date', table_name='fact_ozon_price_snapshot')
    op.drop_index('idx_fact_ozon_price_snapshot_at_offer_id', table_name='fact_ozon_price_snapshot')
    op.drop_table('fact_ozon_price_snapshot')
    # ### end Alembic commands ###
