"""add_wb_seller_price_snapshot

Revision ID: e427673e94e3
Revises: 1740e3cb76da
Create Date: 2026-06-29 14:03:18.732797

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e427673e94e3'
down_revision: Union[str, None] = '1740e3cb76da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_wb_seller_price_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('chrt_id', sa.BigInteger(), nullable=False),
    sa.Column('tech_size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('seller_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_wb_seller_price_snapshot')),
    sa.UniqueConstraint('snapshot_date', 'nm_id', 'chrt_id', name='uq_fact_wb_seller_price_snapshot_date_nm_chrt')
    )
    op.create_index('idx_fact_wb_seller_price_snapshot_date_nm_chrt', 'fact_wb_seller_price_snapshot', ['snapshot_date', 'nm_id', 'chrt_id'], unique=False)
    op.drop_column('fact_ad_cost_day', 'campaign_type')
    op.drop_column('fact_ad_cost_day', 'payment_model')
    op.drop_column('mart_total_report', 'ad_campaign_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mart_total_report', sa.Column('ad_campaign_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fact_ad_cost_day', sa.Column('payment_model', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('fact_ad_cost_day', sa.Column('campaign_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index('idx_fact_wb_seller_price_snapshot_date_nm_chrt', table_name='fact_wb_seller_price_snapshot')
    op.drop_table('fact_wb_seller_price_snapshot')
    # ### end Alembic commands ###
