from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Iterable, Tuple


SERVICE_COLUMNS: Tuple[str, str, str] = ("data_status", "source_status", "loaded_at")


@dataclass(frozen=True)
class SheetSchema:
    name: str
    object_type: str
    columns: Tuple[str, ...]
    primary_key: Tuple[str, ...] = ()
    status_fields: Tuple[str, ...] = ("data_status", "source_status")
    source_fields: Tuple[str, ...] = ()
    notes: str = ""

    def with_service_columns(self) -> "SheetSchema":
        columns = list(self.columns)
        for column in SERVICE_COLUMNS:
            if column not in columns:
                columns.append(column)
        return SheetSchema(
            name=self.name,
            object_type=self.object_type,
            columns=tuple(columns),
            primary_key=self.primary_key,
            status_fields=self.status_fields,
            source_fields=self.source_fields,
            notes=self.notes,
        )


REQUIRED_USER_SHEET_NAMES = [
    "README",
    "Coverage",
    "Backlog",
    "Validation_v1",
    "ИТОГО",
    "ИТОГО_FULL",
    "ИТОГО_v1",
    "Воронка на день",
    "РасходРК",
    "РК стата",
    "ВБро",
    "Точка вх",
    "Локализация",
    "Сравнение карточек",
    "Поисковые запросы",
    "Остатки",
]

REQUIRED_PROCESSED_TABLE_NAMES = [
    "dim_product",
    "fact_funnel_day",
    "fact_stock_snapshot",
    "fact_stock_day",
    "fact_ad_cost_event",
    "fact_ad_cost_day",
    "fact_ad_campaign_day",
    "fact_ad_campaign_nm_day",
    "fact_search_query_metric",
    "fact_profit_day",
    "fact_entry_point_day",
    "entry_points_wide",
    "fact_localization_region_day",
    "fact_localization_region_summary_day",
    "fact_card_comparison_metric",
    "fact_mpstat_item_day",
]


USER_SHEET_SCHEMAS: Dict[str, SheetSchema] = {
    "README": SheetSchema(
        name="README",
        object_type="user_sheet",
        columns=("section", "value", "notes"),
        notes="Project overview and sheet usage notes.",
    ),
    "Coverage": SheetSchema(
        name="Coverage",
        object_type="user_sheet",
        columns=("sheet_name", "status", "details"),
        notes="Coverage summary for sheet structure and sources.",
    ),
    "Backlog": SheetSchema(
        name="Backlog",
        object_type="user_sheet",
        columns=("block", "status", "reason", "next_step", "priority"),
        notes="Items not fully covered by confirmed sources.",
    ),
    "Validation_v1": SheetSchema(
        name="Validation_v1",
        object_type="user_sheet",
        columns=(
            "sheet_name",
            "date",
            "nm_id",
            "impressions",
            "card_clicks",
            "ctr",
            "reason",
        ),
        notes="Data quality validation checklist.",
    ),
    "ИТОГО": SheetSchema(
        name="ИТОГО",
        object_type="user_sheet",
        columns=("date", "nm_id", "supplier_article"),
        notes="Wide full report base columns. Dynamic blocks are added later.",
    ),
    "ИТОГО_FULL": SheetSchema(
        name="ИТОГО_FULL",
        object_type="user_sheet",
        columns=("date", "nm_id", "supplier_article"),
        notes="Wide full report base columns. Dynamic blocks are added later.",
    ),
    "ИТОГО_v1": SheetSchema(
        name="ИТОГО_v1",
        object_type="user_sheet",
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "impressions",
            "card_clicks",
            "ctr",
            "cartCount",
            "orderCount",
            "orderSum",
            "buyoutCount",
            "buyoutSum",
            "buyoutPercent",
            "addToCartConversion",
            "cartToOrderConversion",
            "addToWishlistCount",
            "ad_views",
            "ad_clicks",
            "ad_ctr",
            "ad_cpc",
            "ad_orders",
            "ad_atbs",
            "ad_spend",
            "ad_revenue",
            "cost_per_cart",
            "cpm",
            "cpo",
            "search_queries_count",
            "avg_position",
            "visibility",
            "search_clicks",
            "search_cart",
            "search_orders",
            "current_stockCount",
            "current_stockSum",
            "stock_snapshot_date",
            *SERVICE_COLUMNS,
        ),
    ),
    "Воронка на день": SheetSchema(
        name="Воронка на день",
        object_type="user_sheet",
        columns=(
            "Дата",
            "Артикул продавца",
            "Артикул WB",
            "Название",
            "Предмет",
            "Бренд",
            "Удаленный товар",
            "Рейтинг карточки",
            "Рейтинг по отзывам",
            "Показы",
            "Показы (предыдущий период)",
            "CTR",
            "CTR (предыдущий период)",
            "Доля карточки в выручке",
            "Доля карточки в выручке (предыдущий период)",
            "Переходы в карточку",
            "Переходы в карточку (предыдущий период)",
            "Положили в корзину",
            "Положили в корзину (предыдущий период)",
            "Добавили в отложенные",
            "Добавили в отложенные (предыдущий период)",
            "Заказали товаров, шт",
            "Заказали товаров, шт (предыдущий период)",
            "Выкупили, шт",
            "Выкупили, шт (предыдущий период)",
            "Отменили, шт",
            "Отменили, шт (предыдущий период)",
            "Конверсия в корзину, %",
            "Конверсия в корзину, % (предыдущий период)",
            "Конверсия в заказ, %",
            "Конверсия в заказ, % (предыдущий период)",
            "Процент выкупа",
            "Процент выкупа (предыдущий период)",
            "Заказали на сумму, ₽",
            "Заказали на сумму, ₽ (предыдущий период)",
            "Динамика суммы заказов, ₽",
            "Выкупили на сумму, ₽",
            "Выкупили на сумму, ₽ (предыдущий период)",
            "Отменили на сумму, ₽",
            "Отменили на сумму, ₽ (предыдущий период)",
            "Средняя цена, ₽",
            "Средняя цена, ₽ (предыдущий период)",
            "Среднее количество заказов в день, шт",
            "Среднее количество заказов в день, шт (предыдущий период)",
            "Остатки склад ВБ, шт",
            "Остатки МП, шт",
            "Сумма остатков на складах, ₽",
            "Среднее время доставки",
            "Среднее время доставки (предыдущий период)",
            "Локальные заказы, %",
            "Локальные заказы, % (предыдущий период)",
            "Заказали ВБ клуб, шт",
            "Заказали ВБ клуб, шт (предыдущий период)",
            "Выкупили ВБ клуб, шт",
            "Выкупили ВБ клуб, шт (предыдущий период)",
            "Отменили ВБ клуб, шт",
            "Отменили ВБ клуб, шт (предыдущий период)",
            "Процент выкупа ВБ клуб",
            "Процент выкупа ВБ клуб (предыдущий период)",
            "Заказали на сумму ВБ клуб, ₽",
            "Заказали на сумму ВБ клуб, ₽ (предыдущий период)",
            "Динамика суммы заказов ВБ клуб, ₽",
            "Выкупили на сумму ВБ клуб, ₽",
            "Выкупили на сумму ВБ клуб, ₽ (предыдущий период)",
            "Отменили на сумму ВБ клуб, ₽",
            "Отменили на сумму ВБ клуб, ₽ (предыдущий период)",
            "Среднее количество заказов в день ВБ клуб, шт",
            "Среднее количество заказов в день ВБ клуб, шт (предыдущий период)",
            "процент показов рекламных",
            "показы РК",
            "переплат за корзину в сравнении со вчера",
            "конверсия из показа в корзину",
            "стоимость клика за кабинет",
            "стоимость корзины за кабинет",
            "стоимость заказа за кабинет (CPO)",
            "стоимость 1000 показов за кабинет",
            "рк",
            *SERVICE_COLUMNS,
        ),
    ),
    "РасходРК": SheetSchema(
        name="РасходРК",
        object_type="user_sheet",
        columns=(
            "ID кампании",
            "Кампания",
            "Раздел",
            "Дата списания",
            "Источник списания",
            "Сумма",
            "Номер документа",
            "nm_id",
            "nm_id_parse_status",
            "campaign_type",
            *SERVICE_COLUMNS,
        ),
    ),
    "РК стата": SheetSchema(
        name="РК стата",
        object_type="user_sheet",
        columns=(
            "Дата",
            "ID кампании",
            "Название кампании",
            "Тип строки",
            "Тип конверсии",
            "Номенклатура",
            "Название товара",
            "Затраты, ₽",
            "Выручка, ₽",
            "Показы",
            "Клики",
            "Добавления в корзину",
            "Заказы",
            "Заказанные товары, шт.",
            "Отмены",
            "Средняя позиция",
            "CTR, %",
            "CPC, ₽",
            "CPM, ₽",
            "CR, %",
            "ROI, %",
            *SERVICE_COLUMNS,
        ),
    ),
    "ВБро": SheetSchema(
        name="ВБро",
        object_type="user_sheet",
        columns=(
            "Дата",
            "Артикул ВБ",
            "Артикул продавца",
            "Продажи (органические)",
            "Операционная прибыль",
            "Операционная прибыль на единицу",
            *SERVICE_COLUMNS,
        ),
    ),
    "Точка вх": SheetSchema(
        name="Точка вх",
        object_type="user_sheet",
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "section",
            "entry_point",
            "metric_name",
            "metric_value",
            *SERVICE_COLUMNS,
        ),
        notes="Structure only. Source remains PARTIAL/LATER.",
    ),
    "Локализация": SheetSchema(
        name="Локализация",
        object_type="user_sheet",
        columns=(
            "Дата",
            "Артикул WB",
            "Артикул продавца",
            "Название",
            "Предмет",
            "Бренд",
            "Регион",
            "Итого заказов, шт",
            "Продажи, шт",
            "Сумма продаж, ₽",
            "Остатки склад ВБ, шт",
            "Остатки МП, шт",
            "Время доставки",
            "Локальные заказы, %",
            "Не локальные заказы, %",
            *SERVICE_COLUMNS,
        ),
        notes="Wide human-readable view. Processed tables remain unchanged.",
    ),
    "Сравнение карточек": SheetSchema(
        name="Сравнение карточек",
        object_type="user_sheet",
        columns=(
            "period_start",
            "period_end",
            "base_nm_id",
            "compared_nm_id",
            "metric_group",
            "metric_name",
            "metric_value",
            *SERVICE_COLUMNS,
        ),
    ),
    "Поисковые запросы": SheetSchema(
        name="Поисковые запросы",
        object_type="user_sheet",
        columns=(
            "Артикул продавца",
            "Артикул WB",
            "Название",
            "Предмет",
            "Бренд",
            "Рейтинг карточки",
            "Рейтинг по отзывам",
            "Поисковый запрос",
            "Количество запросов",
            "Количество запросов (предыдущий период)",
            "Видимость, %",
            "Видимость, % (предыдущий период)",
            "Средняя позиция",
            "Средняя позиция (предыдущий период)",
            "Медианная позиция",
            "Медианная позиция (предыдущий период)",
            "Переходы в карточку",
            "Переходы в карточку (предыдущий период)",
            "Переходы в карточку больше, чем у n% карточек конкурентов, %",
            "Положили в корзину",
            "Положили в корзину (предыдущий период)",
            "Положили в корзину больше, чем n% карточек конкурентов, %",
            "Конверсия в корзину, %",
            "Конверсия в корзину, % (предыдущий период)",
            "Конверсия в корзину больше, чем у n% карточек конкурентов, %",
            "Заказали, шт",
            "Заказали, шт (предыдущий период)",
            "Заказали больше, чем n% карточек конкурентов, %",
            "Конверсия в заказ, %",
            "Конверсия в заказ, % (предыдущий период)",
            "Конверсия в заказ больше, чем у n% карточек конкурентов, %",
            "Минимальная цена со скидкой (по размерам), ₽",
            "Максимальная цена со скидкой (по размерам), ₽",
            *SERVICE_COLUMNS,
        ),
    ),
    "Остатки": SheetSchema(
        name="Остатки",
        object_type="user_sheet",
        columns=(
            "snapshot_date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "wb_stock_qty",
            "mp_stock_qty",
            "stock_total_qty",
            "stock_total_sum",
            "saleRate",
            "toClientCount",
            "fromClientCount",
            "availability",
            *SERVICE_COLUMNS,
        ),
    ),
}


PROCESSED_TABLE_SCHEMAS: Dict[str, SheetSchema] = {
    "dim_product": SheetSchema(
        name="dim_product",
        object_type="processed_table",
        primary_key=("nm_id",),
        source_fields=("supplier_article", "category", "brand"),
        columns=(
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "category",
            "brand",
            "is_deleted",
            "card_rating",
            "reviews_rating",
            "reviews_count",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_funnel_day": SheetSchema(
        name="fact_funnel_day",
        object_type="processed_table",
        primary_key=("date", "nm_id"),
        source_fields=("supplier_article", "title", "subject", "brand"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "impressions",
            "impressions_prev",
            "card_clicks",
            "card_clicks_prev",
            "ctr",
            "ctr_prev",
            "revenue_share_percent",
            "revenue_share_percent_prev",
            "cartCount",
            "cartCount_prev",
            "addToWishlistCount",
            "addToWishlistCount_prev",
            "orderCount",
            "orderCount_prev",
            "buyoutCount",
            "buyoutCount_prev",
            "cancelCount",
            "cancelCount_prev",
            "addToCartConversion",
            "addToCartConversion_prev",
            "cartToOrderConversion",
            "cartToOrderConversion_prev",
            "buyoutPercent",
            "buyoutPercent_prev",
            "orderSum",
            "orderSum_prev",
            "orderSumDynamics",
            "buyoutSum",
            "buyoutSum_prev",
            "cancelSum",
            "cancelSum_prev",
            "avg_price",
            "avg_price_prev",
            "avg_orders_per_day",
            "avg_orders_per_day_prev",
            "avg_delivery_time",
            "avg_delivery_time_prev",
            "local_orders_percent",
            "local_orders_percent_prev",
            "wbclub_orderCount",
            "wbclub_orderCount_prev",
            "wbclub_buyoutCount",
            "wbclub_buyoutCount_prev",
            "wbclub_cancelCount",
            "wbclub_cancelCount_prev",
            "wbclub_buyoutPercent",
            "wbclub_buyoutPercent_prev",
            "wbclub_orderSum",
            "wbclub_orderSum_prev",
            "wbclub_orderSumDynamics",
            "wbclub_buyoutSum",
            "wbclub_buyoutSum_prev",
            "wbclub_cancelSum",
            "wbclub_cancelSum_prev",
            "wbclub_avg_orders_per_day",
            "wbclub_avg_orders_per_day_prev",
            "b2b_orderCount",
            "b2b_orderCount_prev",
            "b2b_buyoutCount",
            "b2b_buyoutCount_prev",
            "b2b_cancelCount",
            "b2b_cancelCount_prev",
            "b2b_orderSum",
            "b2b_orderSum_prev",
            "b2b_buyoutSum",
            "b2b_buyoutSum_prev",
            "b2b_cancelSum",
            "b2b_cancelSum_prev",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_stock_snapshot": SheetSchema(
        name="fact_stock_snapshot",
        object_type="processed_table",
        primary_key=("snapshot_date", "nm_id"),
        source_fields=("supplier_article", "title", "subject", "brand"),
        columns=(
            "snapshot_date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "wb_stock_qty",
            "mp_stock_qty",
            "stock_total_qty",
            "stock_total_sum",
            "saleRate",
            "toClientCount",
            "fromClientCount",
            "availability",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_stock_day": SheetSchema(
        name="fact_stock_day",
        object_type="processed_table",
        primary_key=("date", "nm_id"),
        source_fields=("supplier_article", "title", "subject", "brand"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "wb_stock_qty",
            "mp_stock_qty",
            "stock_total_qty",
            "stock_total_sum",
            "saleRate",
            "toClientCount",
            "fromClientCount",
            "availability",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_ad_cost_event": SheetSchema(
        name="fact_ad_cost_event",
        object_type="processed_table",
        primary_key=("date", "advertId", "writeoff_datetime", "document_number"),
        source_fields=("campaign_name", "section_raw", "writeoff_source", "campaign_type"),
        columns=(
            "date",
            "advertId",
            "campaign_name",
            "section_raw",
            "writeoff_datetime",
            "writeoff_source",
            "spend",
            "document_number",
            "nm_id_from_section",
            "nm_id_from_campaign_name",
            "nm_id",
            "nm_id_parse_status",
            "campaign_type",
            "currency",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_ad_cost_day": SheetSchema(
        name="fact_ad_cost_day",
        object_type="processed_table",
        primary_key=("date", "advertId", "nm_id"),
        source_fields=("campaign_name", "allocation_status"),
        columns=(
            "date",
            "advertId",
            "campaign_name",
            "nm_id",
            "total_spend",
            "events_count",
            "allocation_status",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_ad_campaign_day": SheetSchema(
        name="fact_ad_campaign_day",
        object_type="processed_table",
        primary_key=("date", "advertId", "row_type"),
        source_fields=("campaign_name", "row_type"),
        columns=(
            "date",
            "advertId",
            "campaign_name",
            "row_type",
            "ad_spend",
            "ad_revenue",
            "ad_views",
            "ad_clicks",
            "ad_atbs",
            "ad_orders",
            "ordered_items_qty",
            "ad_cancels",
            "avg_position",
            "ad_ctr",
            "ad_cpc",
            "ad_cpm",
            "ad_cr",
            "ad_roi",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_ad_campaign_nm_day": SheetSchema(
        name="fact_ad_campaign_nm_day",
        object_type="processed_table",
        primary_key=("date", "advertId", "row_type", "conversion_type", "nm_id"),
        source_fields=("campaign_name", "row_type", "conversion_type_raw", "product_name"),
        columns=(
            "date",
            "advertId",
            "campaign_name",
            "row_type",
            "conversion_type",
            "conversion_type_raw",
            "nm_id",
            "product_name",
            "ad_spend",
            "ad_revenue",
            "ad_views",
            "ad_clicks",
            "ad_atbs",
            "ad_orders",
            "ordered_items_qty",
            "ad_cancels",
            "avg_position",
            "ad_ctr",
            "ad_cpc",
            "ad_cpm",
            "ad_cr",
            "ad_roi",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_search_query_metric": SheetSchema(
        name="fact_search_query_metric",
        object_type="processed_table",
        primary_key=("period_start", "period_end", "nm_id", "search_query"),
        source_fields=("supplier_article", "title", "subject", "brand"),
        columns=(
            "period_start",
            "period_end",
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "card_rating",
            "reviews_rating",
            "search_query",
            "query_count",
            "query_count_prev",
            "visibility",
            "visibility_prev",
            "avg_position",
            "avg_position_prev",
            "median_position",
            "median_position_prev",
            "search_clicks",
            "search_clicks_prev",
            "search_clicks_competitor_percentile",
            "search_cart",
            "search_cart_prev",
            "search_cart_competitor_percentile",
            "cart_conversion",
            "cart_conversion_prev",
            "cart_conversion_competitor_percentile",
            "search_orders",
            "search_orders_prev",
            "search_orders_competitor_percentile",
            "order_conversion",
            "order_conversion_prev",
            "order_conversion_competitor_percentile",
            "min_discount_price",
            "max_discount_price",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_profit_day": SheetSchema(
        name="fact_profit_day",
        object_type="processed_table",
        primary_key=("date", "nm_id"),
        source_fields=("supplier_article", "title", "subject", "brand"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "organic_sales_qty",
            "net_sales_payout",
            "ad_spend",
            "logistics",
            "storage",
            "penalties",
            "deductions",
            "acceptance",
            "cogs",
            "other_costs",
            "operating_profit",
            "operating_profit_per_unit",
            "formula_status",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_entry_point_day": SheetSchema(
        name="fact_entry_point_day",
        object_type="processed_table",
        primary_key=("date", "nm_id", "section", "entry_point"),
        source_fields=("supplier_article", "title", "section", "entry_point"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "section",
            "entry_point",
            "impressions",
            "card_clicks",
            "ctr",
            "cart_count",
            "add_to_cart_conversion",
            "order_count",
            "order_conversion",
            "metric_name",
            "metric_value",
            "orders_qty",
            "revenue",
            "source_file_name",
            *SERVICE_COLUMNS,
        ),
    ),
    "entry_points_wide": SheetSchema(
        name="entry_points_wide",
        object_type="processed_table",
        primary_key=("date", "nm_id"),
        source_fields=("supplier_article", "title"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "entry_points_payload",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_localization_region_day": SheetSchema(
        name="fact_localization_region_day",
        object_type="processed_table",
        primary_key=("date", "nm_id", "region"),
        source_fields=("supplier_article", "title", "country", "region", "city"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "country",
            "region",
            "city",
            "delivery_time",
            "orders_total_qty",
            "orders_local_qty",
            "orders_nonlocal_qty",
            "orders_nonlocal_percent",
            "wb_stock_orders_local_qty",
            "wb_stock_orders_nonlocal_qty",
            "wb_stock_orders_nonlocal_percent",
            "mp_orders_local_qty",
            "mp_orders_nonlocal_qty",
            "mp_orders_nonlocal_percent",
            "wb_stock_qty",
            "mp_stock_qty",
            "sale_item_qty",
            "sale_amount",
            "delivery_time_text",
            "local_orders_percent",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_localization_region_summary_day": SheetSchema(
        name="fact_localization_region_summary_day",
        object_type="processed_table",
        primary_key=("date", "region"),
        source_fields=("country", "region"),
        columns=(
            "date",
            "country",
            "region",
            "sale_item_qty",
            "sale_amount",
            "local_orders_percent",
            "nonlocal_orders_percent",
            "delivery_time",
            "region_orders_share_percent",
            "wb_all_orders_share_percent",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_card_comparison_metric": SheetSchema(
        name="fact_card_comparison_metric",
        object_type="processed_table",
        primary_key=("period_start", "period_end", "base_nm_id", "compared_nm_id", "metric_name"),
        source_fields=("metric_group",),
        columns=(
            "period_start",
            "period_end",
            "base_nm_id",
            "compared_nm_id",
            "metric_group",
            "metric_name",
            "metric_value",
            *SERVICE_COLUMNS,
        ),
    ),
    "fact_mpstat_item_day": SheetSchema(
        name="fact_mpstat_item_day",
        object_type="processed_table",
        primary_key=("date", "nm_id"),
        source_fields=("supplier_article", "title", "subject", "brand"),
        columns=(
            "date",
            "nm_id",
            "supplier_article",
            "title",
            "subject",
            "brand",
            "card_rating",
            "reviews_rating",
            "avg_delivery_time",
            "avg_position",
            "impressions",
            "card_clicks",
            "search_cart",
            "search_orders",
            "buyouts",
            "ctr",
            "cart_conversion",
            "order_conversion",
            "buyout_percent",
            *SERVICE_COLUMNS,
        ),
    ),
}


def iter_all_schemas() -> Iterable[SheetSchema]:
    yield from USER_SHEET_SCHEMAS.values()
    yield from PROCESSED_TABLE_SCHEMAS.values()
